# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13uu_CSUtA4GQd-OXebSl8pBYwtER1UNA
"""

pip install newspaper3k

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from newspaper import Article

urls=[
"https://medium.com/@nutanbhogendrasharma/access-news-in-python-using-the-newspaper3k-package-d3edb6561580",
"https://medium.com/gitconnected/the-resume-that-got-a-software-engineer-a-300-000-job-at-google-8c5a1ecff40f",
"https://medium.com/gitconnected/stop-using-uuids-in-your-database-aae9d5d47549",
"https://medium.com/itnext/why-tdd-is-a-waste-of-time-9f08ddfb0994",
"https://medium.com/itnext/become-a-better-developer-with-10-principles-911b6252e881"
]

def ex(url):
  for i in url:
    p=Article(i)
    p.download()
    p.parse()
    return (p.text)

L=[[ex([i])] for i in urls]

l=[]
for i in L:
  if i!='/n' or i!=" ":
    l.append(i)

pip install langchain_community

pip install langchain_chroma

from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_chroma import Chroma

pip install -U sentence-transformers

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('sentence-transformers/paraphrase-MiniLM-L6-v2')

from sklearn.metrics.pairwise import cosine_similarity

s={}
for i in range(5):
  h=[]
  for j in range(5):
    if i!=j:
      p=cosine_similarity(model.encode(l[i]),model.encode(l[j]))[0][0]
      per=(p*100)
      h.append(per)
  s[i]=h

for i in s:
  print("rec part of user",i,"is",s[i].index(sorted(s[i])[-2]))

for i in range(len(s)):
  print(i,s[i])
